# Created with https://github.com/dart-lang/mono_repo
language: dart

# Custom configuration
before_install:
  - chmod +x ./tool/travis.sh
sudo: required

jobs:
  include:
    - stage: analyze
      name: "SDK: stable - DIR: kiwi - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="kiwi"
      dart: stable
    - stage: analyze
      name: "SDK: dev - DIR: kiwi - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="kiwi"
      dart: dev
    - stage: analyze
      name: "SDK: stable - DIR: kiwi - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="kiwi"
      dart: stable
    - stage: analyze
      name: "SDK: dev - DIR: kiwi - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="kiwi"
      dart: dev
    - stage: unit_test
      name: "SDK: stable - DIR: kiwi - TASKS: pub run test"
      script: ./tool/travis.sh test
      env: PKG="kiwi"
      dart: stable
    - stage: unit_test
      name: "SDK: dev - DIR: kiwi - TASKS: pub run test"
      script: ./tool/travis.sh test
      env: PKG="kiwi"
      dart: dev
    - stage: analyze
      name: "SDK: stable - DIR: kiwi_generator - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="kiwi_generator"
      dart: stable
    - stage: analyze
      name: "SDK: dev - DIR: kiwi_generator - TASKS: dartfmt -n --set-exit-if-changed ."
      script: ./tool/travis.sh dartfmt
      env: PKG="kiwi_generator"
      dart: dev
    - stage: analyze
      name: "SDK: stable - DIR: kiwi_generator - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="kiwi_generator"
      dart: stable
    - stage: analyze
      name: "SDK: dev - DIR: kiwi_generator - TASKS: dartanalyzer --fatal-infos --fatal-warnings ."
      script: ./tool/travis.sh dartanalyzer
      env: PKG="kiwi_generator"
      dart: dev
    - stage: unit_test
      name: "SDK: stable - DIR: kiwi_generator - TASKS: pub run test"
      script: ./tool/travis.sh test
      env: PKG="kiwi_generator"
      dart: stable
    - stage: unit_test
      name: "SDK: dev - DIR: kiwi_generator - TASKS: pub run test"
      script: ./tool/travis.sh test
      env: PKG="kiwi_generator"
      dart: dev

stages:
  - analyze
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
