name: build_all

on:
  push:
    branches: [ 'master', 'stable' ]
  pull_request:
    branches: [ 'master', 'stable' ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ stable ]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.15.0
        with:
          channel: ${{ matrix.version }}
      - name: Build & format for flutter_kiwi example
        run: |
          cd examples/flutter_kiwi
          flutter packages get
          flutter packages pub run build_runner build --delete-conflicting-outputs
          dart format --line-length 160 .
      - name: Use verify-changed-files to check if any of the above files changed.
        uses: tj-actions/verify-changed-files@v18
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"
  dart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ stable, beta, dev ]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Build & format for kiwi_generator
        run: |
          cd packages/kiwi_generator
          dart pub get
          dart run build_runner build --delete-conflicting-outputs
          dart format --line-length 160 .
      - name: Build & format for dart_kiwi example
        run: |
          cd examples/dart_kiwi
          dart pub get
          dart run build_runner build --delete-conflicting-outputs
          dart format --line-length 160 .
      - name: Use verify-changed-files to check if any of the above files changed.
        uses: tj-actions/verify-changed-files@v18
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"          

